export const GET_CATEGORY_ERRORS = 'GET_CATEGORY_ERRORS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORY = 'GET_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const GET_PROJECT_ERRORS = 'GET_PROJECT_ERRORS'
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECT = 'GET_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const GET_ASSIGNED_PROJECTS = "GET_ASSIGNED_PROJECTS"

export const GET_TASK_ERRORS = 'GET_TASK_ERRORS'
export const GET_TASKS = 'GET_TASKS'
export const GET_TASK = 'GET_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const GET_ASSIGNED_TASKS = "GET_ASSIGNED_TASKS"
export const DELETE_ASSIGNED_TASK = "DELETE_ASSIGNED_TASK"

export const GET_FILE_ERRORS = 'GET_FILE_ERRORS'
export const GET_FILES = 'GET_FILES'
export const GET_FILE = 'GET_FILE'
export const DELETE_FILE = 'DELETE_FILE'

export const CLOSE_UPLOAD_MODAL = 'CLOSE_UPLOAD_MODAL'
export const OPEN_UPLOAD_MODAL = 'OPEN_UPLOAD_MODAL'
export const SET_FILE_UPLOADED_TRUE = 'SET_FILE_UPLOADED_TRUE'
export const SET_FILE_UPLOADED_FALSE = 'SET_FILE_UPLOADED_FALSE'

export const GET_ERRORS = 'GET_ERRORS'
export const GET_LOGIN_ERRORS = 'GET_LOGIN_ERRORS'
export const GET_REGISTRATION_ERRORS = 'GET_REGISTRATION_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION'

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'
export const GET_PROJECT_ACTIVITY = 'GET_PROJECT_ACTIVITY'
export const GET_TASK_ACTIVITY = 'GET_TASK_ACTIVITY'
export const GET_USER_ACTIVITY = 'GET_USER_ACTIVITY'
export const GET_ACTIVITY_ERRORS = 'GET_ACTIVITY_ERRORS'

export const CONFIRM_PASSWORD_RESET = "CONFIRM_PASSWORD_RESET"
export const CONFIRM_PASSWORD_RESET_ERRORS = "CONFIRM_PASSWORD_RESET_ERRORS"

export const GET_USER_ERRORS = "GET_USER_ERRORS"
export const GET_USER_INFO = "GET_USER_INFO"
export const GET_PRIVATE_USER_PROFILE = "GET_PRIVATE_USER_PROFILE"
export const DELETE_USER = "DELETE_USER"
export const GET_USER_CONTACTS = "GET_USER_CONTACTS"
export const UPDATE_USER_INFO = "UPDATE_USER_INFO"

export const GET_WORKING_TIME_ERRORS = "GET_WORKING_TIME_ERRORS"
export const GET_WORKING_TIME = "GET_WORKING_TIME"
export const GET_LOGS = "GET_LOGS"
