export const GET_CATEGORY_ERRORS = "GET_CATEGORY_ERRORS"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = "GET_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"

export const GET_PROJECT_ERRORS = "GET_PROJECT_ERRORS"
export const GET_PROJECTS = "GET_PROJECTS"
export const GET_PROJECT = "GET_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const GET_TASK_ERRORS = "GET_PROJECT_ERRORS"
export const GET_TASKS = "GET_PROJECTS"
export const GET_TASK = "GET_PROJECT"
export const DELETE_TASK = "DELETE_PROJECT"
